/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.toubou.librarymanagement;

/**
 *
 * @author theo
 */
public class Librarian extends javax.swing.JFrame {

    /** Creates new form LibrarianAdministration */
    public Librarian() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titlesJButton = new javax.swing.JButton();
        lendingsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        membersJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian Main Adminstration Panel");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 255));

        jLabel4.setText("Library Management System | v0.1 - Beta Version | All Rights Reserved © ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select the category you prefer to administrate :", 0, 0, new java.awt.Font("Harlow Solid Italic", 0, 24), new java.awt.Color(0, 108, 91))); // NOI18N

        jLabel2.setText("Title/Item Administration");

        titlesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/toubou/librarymanagement/books.png"))); // NOI18N
        titlesJButton.setBorder(new javax.swing.border.MatteBorder(null));
        titlesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlesJButtonActionPerformed(evt);
            }
        });

        lendingsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/toubou/librarymanagement/blue-bidirectional-arrow.png"))); // NOI18N
        lendingsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendingsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Member Administration");

        membersJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/toubou/librarymanagement/Student-id-icon.png"))); // NOI18N
        membersJButton.setBorder(new javax.swing.border.MatteBorder(null));
        membersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Lendings Administration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(membersJButton))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lendingsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlesJButton)
                    .addComponent(lendingsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(membersJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/*according to each button press, the corresponding Librarian's method will be called*/
//matching buttons to methods
    private void membersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersJButtonActionPerformed
        members();
    }//GEN-LAST:event_membersJButtonActionPerformed

    private void titlesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlesJButtonActionPerformed
        titles();
    }//GEN-LAST:event_titlesJButtonActionPerformed

    private void lendingsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendingsJButtonActionPerformed
        lendings();
    }//GEN-LAST:event_lendingsJButtonActionPerformed
//end of matching buttons to methods
    
    
    //Librarian's method to handle a Member object
    public void members()
    {
        MemberAdministration member = new MemberAdministration();
        member.setVisible(true);
    }
    
    //Librarian's method to handle a Title object
    public void titles()
    {
        TitleAdministration title = new TitleAdministration();
        title.setVisible(true);
    }
    
    //Librarian's method to handle a lending
    public void lendings()
    {
        LendingsAdministration lending = new LendingsAdministration();
        lending.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lendingsJButton;
    private javax.swing.JButton membersJButton;
    private javax.swing.JButton titlesJButton;
    // End of variables declaration//GEN-END:variables
}
